### ISSUE TITLE
grasp refinement head

### ISSUE THREAD

**Issue by qingchenkanlu** [stefan-ainetter/grasp_det_seg_cnn#1]
Hi! can you point out where is the grasp refinement head, I have not found it in this repository. Thanks!

**Comment by stefan-ainetter** [comment]
Hi @qingchenkanlu,
The code for the grasp refinement head is not part of this repository, as it only contains the code for the experiment in Section VI.D in our paper.
I don't know yet at which point we will release this code.
However, the paper should contain all the necessary information to re-implement the grasp refinement head, if you want to do so in the meantime.
