### ISSUE TITLE
train model

### ISSUE THREAD

**Issue by jim88481** [stefan-ainetter/grasp_det_seg_cnn#10]
Can anyone provide the train model, the author gave the model to download down to show that the file is corrupted.thanks

**Comment by stefan-ainetter** [comment]
Hi @jim88481,
I downloaded the files by myself and checked again, everything works for me. So the provided files are not corrupted. Please try again to download the files.

**Comment by aakaash06** [comment]
@stefan-ainetter even i got this error. When I extract the file it says it is corrupted
