### ISSUE TITLE
hello!

### ISSUE THREAD

**Issue by meiguiz** [stefan-ainetter/grasp_det_seg_cnn#11]
hello!I see in you readme,I need to use torch.distributed.launch --nproc_per_node=1,but I only have one gpu,can I train you network?
thank you very much!this is my bug.
![2022-05-07 19-30-47屏幕截图](https://user-images.githubusercontent.com/90629126/167252352-1ab88770-b046-45f3-a6d8-7bfc82e9fdcb.png)

**Comment by stefan-ainetter** [comment]
Hi,
yes, it is possible to train the network with only one gpu. In fact, the code and config files provided in this repository are intended for single gpu usage. So if you follow the instructions in the ReadMe, it should work fine with one gpu.
About your error, I am not sure where this exactly comes from. You should maybe check again if your system meets all necessary requirements.

**Comment by scq6688** [comment]
> hello!I see in you readme,I need to use torch.distributed.launch --nproc_per_node=1,but I only have one gpu,can I train you network? thank you very much!this is my bug. ![2022-05-07 19-30-47屏幕截图](https://user-images.githubusercontent.com/90629126/167252352-1ab88770-b046-45f3-a6d8-7bfc82e9fdcb.png)

请问您跑通这个代码了吗？方便加微信交流下吗？18862013809
