### ISSUE TITLE
folder path

### ISSUE THREAD

**Issue by github-lile** [stefan-ainetter/grasp_det_seg_cnn#14]
Hello,I have a question.
where is the folder ‘ckpt_files_OCID/pretrained’ and ‘weights_pretrained’?
Do we need to create the folders ourselves?

**Comment by stefan-ainetter** [comment]
Hi @github-lile,
really sorry for the late reply!
Yes, you are right, these folders were missing. However, I added them in the latest commit.
Thanks for pointing this out! :)
