### ISSUE TITLE
run on cpu

### ISSUE THREAD

**Issue by uuu686** [stefan-ainetter/grasp_det_seg_cnn#18]
hello, can the model run on cpu ?

**Comment by stefan-ainetter** [comment]
The code provided in this repository is intended to use GPUs for training and inference.

**Comment by uuu686** [comment]
Thank you. If I want to use cpu to inference, what should I do? Should I train the model on cpu first ?

**Comment by stefan-ainetter** [comment]
I have no experience with this, but it should be possible to load the parameters from a model trained on the GPU, and use them for inference on the CPU.

**Comment by uuu686** [comment]
Thank you!
