### ISSUE TITLE
evaluation metric

### ISSUE THREAD

**Issue by lindaludovisi** [stefan-ainetter/grasp_det_seg_cnn#2]
I'm sorry, where can I find the evaluation metrics, like the iou and the jaccard index for the test set?

**Comment by stefan-ainetter** [comment]
Hi,
The calculations for the Jaccard index and segmentation IOU are not included in this repository. If you want to implement the evaluation metrics, see detailed information in Section IV. in our paper.

**Comment by stefan-ainetter** [comment]
Evaluation script for calculating Jaccard index and segmentation IOU was added in commit https://github.com/stefan-ainetter/grasp_det_seg_cnn/commit/2492d5ec78f831c327e817246e822cdfce9e16ad.
