### ISSUE TITLE
model_last.pth.tar is damaged

### ISSUE THREAD

**Issue by happymatlab** [stefan-ainetter/grasp_det_seg_cnn#28]
[model_last.pth.tar] is damaged when I download to my desktop. Could you please give another link? Thanks!

**Comment by stefan-ainetter** [comment]
Hi,
here is another link for the model weights:
[model_last.pth.tar](https://files.icg.tugraz.at/f/a39df3cf64a44c3fba1c/?dl=1)

I downloaded and tested the weights on my local PC, so it should work as expected.
