### ISSUE TITLE
can't download the ocid and osd

### ISSUE THREAD

**Issue by alaladingding** [stefan-ainetter/grasp_det_seg_cnn#35]
I can't dowdload The Object Clutter Indoor Dataset (OCID) and Object Segmentation Dataset (OSD) from (https://www.acin.tuwien.ac.at/en/vision-for-robotics/software-tools/object-clutter-indoor-dataset/),dosome someone have the resource?I would greatly appreciate your assistance in obtaining it.

**Comment by stefan-ainetter** [comment]
Hi @alaladingding,
please contact the original authors of the OCID dataset regarding invalid download links. Contact information can be found on the bottom of the OCID [web page](https://www.acin.tuwien.ac.at/en/vision-for-robotics/software-tools/object-clutter-indoor-dataset/).

**Comment by ChunQiu1995** [comment]
> Hi @alaladingding, please contact the original authors of the OCID dataset regarding invalid download links. Contact information can be found on the bottom of the OCID [web page](https://www.acin.tuwien.ac.at/en/vision-for-robotics/software-tools/object-clutter-indoor-dataset/).

Thank you for your suggestion. I emailed the original authors two weeks ago, but I have not received a response from them yet. Additionally, I was able to download the OCID dataset through a certain channel, but I have been unable to download the OSD dataset.

**Comment by Yfanmeng** [comment]
> > Hi @alaladingding, please contact the original authors of the OCID dataset regarding invalid download links. Contact information can be found on the bottom of the OCID [web page](https://www.acin.tuwien.ac.at/en/vision-for-robotics/software-tools/object-clutter-indoor-dataset/).
> 
> Thank you for your suggestion. I emailed the original authors two weeks ago, but I have not received a response from them yet. Additionally, I was able to download the OCID dataset through a certain channel, but I have been unable to download the OSD dataset.

Hello, sorry to bother you.I can't dowdload The Object Clutter Indoor Dataset (OCID)  from (https://www.acin.tuwien.ac.at/en/vision-for-robotics/software-tools/object-clutter-indoor-dataset/),Can you share your resources? I would greatly appreciate your assistance in obtaining it. My e-mail address is yifanmeng99@163.com
