### ISSUE TITLE
learning rate during training

### ISSUE THREAD

**Issue by missqi18** [stefan-ainetter/grasp_det_seg_cnn#4]
hello, I'm training your network, and the learning rate maintain at 0.000 and never change during the first 70/800epoch, and other parameters' change seems normal, is it right?

**Comment by missqi18** [comment]
Thank you very much for your reply！

**Comment by missqi18** [comment]
I notice that  "bn_frozen" should set to "no" in "det_seg_OCID.ini" file, then the learning rate can be normal.

**Comment by uuu686** [comment]
@missqi18 hello, when i run the code,i get some errors: ImportError: cannot import name '_backend'.  It happended when i import pyi files. I dont know how to solve the problem，can you give me some help
