### ISSUE TITLE
the memory during training

### ISSUE THREAD

**Issue by meiguiz** [stefan-ainetter/grasp_det_seg_cnn#8]
how much memory do I need during training?thank you very much!

**Comment by stefan-ainetter** [comment]
Hi @meiguiz,
Approx. 11gb of GPU memory are needed during training if you use the available config file.
The easiest way to reduce the memory consumption is to decrease the batch size (see parameter `train_batch_size` in [det_seg_OCID.ini](https://github.com/stefan-ainetter/grasp_det_seg_cnn/blob/2492d5ec78f831c327e817246e822cdfce9e16ad/grasp_det_seg/config/defaults/det_seg_OCID.ini)) or use the less complex resnet50 backbone as feature extractor (see parameters `body` and `weights`) . For example, if you use `train_batch_size=2` and `body=resnet50`, you will be able to reduce the memory to approx. 3gb.

**Comment by meiguiz** [comment]
thank you very much for you reply!

**Comment by meiguiz** [comment]
thank you very much for you reply!
