### ISSUE TITLE
hello!I have a question

### ISSUE THREAD

**Issue by meiguiz** [stefan-ainetter/grasp_det_seg_cnn#9]
hello!I have a question.Have you tested the mAP and mAR of your semantic segmentation module? If my segmentation does not achieve a high accuracy rate, will it not work well with grasp detection?

**Comment by stefan-ainetter** [comment]
Hi,
for evaluation of the semantic segmentation results, we only considered the mean IOU as we thought this is the most suited evaluation metric for this task.

For your second question: The accuracy for grasp detection can be high, although the results for segmentation are bad. The reason for this is that we have two independent branches for grasp detection and segmentation ( both branches only share the same backbone feature extractor). The only thing that you have to keep in mind is that we use the segmentation results to assign the grasp candidates to the objects. This will not be possible without good segmentation results.
If your dataset does not contain ground truth for semantic segmentation, or the quality of the segmentation ground truth is bad, you can also consider to simply remove the segmentation branch and only use the grasp detection.
